### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by msftcangoblowm** [kaotickj/password-genie#1]
There are two scripts, but no packaging. Each script should be a (testable) entrypoint.

Here is an example published package, with packaging design that works

[repo with nice packaging](https://github.com/msftcangoblowm/logging-strict)

You are welcome to borrow the packaging. Especially the semantic versioning.

**Comment by msftcangoblowm** [comment]
With packaging there would be no need to list the dependencies

The dependencies should be within requirements/*.in files. Which are then expanded into requirements/*.pip files

Using the command `make upgrade`

A pyproject.toml file would then have a section looking similar to (meaning steal this):

```
[tool.setuptools.dynamic]
optional-dependencies.pip = { file = ["requirements/pip.pip"] }
optional-dependencies.pip_tools = { file = ["requirements/pip-tools.pip"] }
dependencies = { file = ["requirements/prod.pip"] }
optional-dependencies.dev = { file = ["requirements/dev.pip"] }
optional-dependencies.manage = { file = ["requirements/manage.pip"] }
optional-dependencies.docs = { file = ["docs/requirements.pip"] }
version = {attr = "logging_strict._version.__version__"}
```

Afterwards can remove the dependencies list from README.[rst|md]

**Comment by kaotickj** [comment]
Not a valid issue.  Matter of personal preference.  Please don't waste my time with this crap.
